name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
  
      - name: Update Buildozer
        run: | 
          python3 -m pip install --upgrade buildozer
          python3 -m pip install --upgrade kivy pyjnius
          pip install jnius
          sudo apt-get install lld
          sudo apt-get install ccache
          pip install cython==0.29.19
          
      - name: Install JDK 8
        run: |
          sudo apt update && sudo apt install -y openjdk-8-jdk-headless
      
          # Get JDK path
          jdk_path=$(readlink -f $(which java))
      
          # Set JDK path in buildozer.spec
          echo "jdk_path=$jdk_path" >> buildozer.spec
          
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential 
          
      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O android-sdk.zip
          unzip -q android-sdk.zip -d android-sdk
          export ANDROID_SDK_ROOT=$PWD/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/bin    
        
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Install AIDL
        run: sudo apt-get install -y aidl
      - name: Print Environment Info
        run: |
          echo "Python Version: $(python3 --version)"
          echo "Python Path: $(which python3)"
          echo "System PATH: $PATH"  
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: |
            echo "y" | buildozer android debug
          buildozer_version: master
        if: ${{ always() }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
